### ISSUE TITLE
make .match the last column?

### ISSUE THREAD

**Issue by gaborcsardi** [MangoTheCat/rematch2#1]
From https://github.com/MangoTheCat/rematch/issues/4.

**Comment by gaborcsardi** [comment]
@jennybc I suppose we can put it at the end. How about putting there some indices, too? Start of match, maybe?

**Comment by jennybc** [comment]
I don't feel very strongly re: sending `.match` to the end btw, but it just seems nice. Also would imply that group i will end up as column i.

I haven't needed position of match yet w/ `rematch[2]?` but that could be handy.

**Comment by gaborcsardi** [comment]
OK, I moved  the `.match` column to be last in the new implementation.

I'll add a new function for the match positions, #2.
